sudo: false
language: node_js
node_js:
  - '8'
  - '10'
install:
  - cd Frontend && npm install && cd ..
script:
  - cd Frontend && npm run compile && cd ..
after_script:
  - cd Frontend && npm install codecov && codecov && cd ..