sudo: false
language: node_js
install:
  - cd Frontend && npm install && cd ..
script:
  - cd Frontend && npm run compile && cd ..
after_script:
  - cd Frontend && npm install codecov && codecov && cd ..
