environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - cd Frontend && npm install && cd ..

test_script:
  - node --version
  - npm --version
  - npm run compile