environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - cd Frontend && npm install && npm run compile && cd ..
  - nuget restore FormCore.sln