environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - cd Frontend && npm install && npm run compile && cd ..
  - nuget restore FormCore.sln

test_script:
  - where vstest.console
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:"/logger:Appveyor FormCoreTest\bin\Debug\FormCoreTest.dll" -output:".\coverage.xml" -filter:"+[FormCore*]* -[FormCoreTest*]*"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 2787e7bb-b119-4f49-8dec-d0ba330d909f